___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" width="450" height="200" title="Welcome to Place Where You can Reinvent Yourself"></a><br/>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [43]:
# YOUR CODE IS HERE

import numpy as np 

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [44]:
# YOUR CODE IS HERE

my_list = [5, 10, 15, 20, 25]
arr = np.array(my_list)
arr

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [45]:
# YOUR CODE IS HERE

arr1 = np.zeros((5,5))
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [46]:
# YOUR CODE IS HERE
arr_ones =np.ones((4,4), dtype = int)
arr_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [47]:
# YOUR CODE IS HERE
arr_ones7 =np.ones((4,4), dtype = int) * 7
arr_ones7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [48]:
# YOUR CODE IS HERE

np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [49]:
# YOUR CODE IS HERE

np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [50]:
# YOUR CODE IS HERE

np.array(range(25)).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [51]:
# YOUR CODE IS HERE
np.linspace(0,25,25, endpoint = False, dtype = int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [52]:
# YOUR CODE IS HERE
np.random.rand(5)

array([0.43898147, 0.31742511, 0.25045131, 0.68511836, 0.84937296])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [53]:
# YOUR CODE IS HERE

np.random.randn(5,5)

array([[ 0.14914136,  0.03993873, -0.3647574 ,  0.03220114,  1.92772862],
       [ 0.25785091, -0.31464388, -2.21813946, -1.03060231,  0.62521217],
       [-0.3913484 ,  1.17310003, -0.31389814, -1.3436706 , -0.27567373],
       [ 0.21911321,  0.48541278,  1.27627151, -1.14460604, -0.630631  ],
       [-0.94209022,  0.77296319,  0.02270029,  0.28159793,  0.76641428]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [54]:
# YOUR CODE IS HERE

np.random.randint(20,50, size= (3,4))

array([[36, 33, 41, 47],
       [44, 31, 30, 45],
       [27, 34, 35, 46]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [55]:
# YOUR CODE IS HERE

ranarr = np.random.randint(1,48,48)
ranarr

array([27, 44,  1, 41, 20, 12, 17, 17, 40, 39, 46,  7, 26,  2,  1, 35, 24,
        8, 35, 27, 44, 38, 17, 31, 33, 16, 38,  8, 32, 42, 18, 34,  9, 10,
       14, 28,  5, 27, 33, 20, 18, 26, 41, 43, 15, 28, 32,  8])

In [56]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr.reshape(6,8)

array([[27, 44,  1, 41, 20, 12, 17, 17],
       [40, 39, 46,  7, 26,  2,  1, 35],
       [24,  8, 35, 27, 44, 38, 17, 31],
       [33, 16, 38,  8, 32, 42, 18, 34],
       [ 9, 10, 14, 28,  5, 27, 33, 20],
       [18, 26, 41, 43, 15, 28, 32,  8]])

In [57]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(6,-1)

array([[27, 44,  1, 41, 20, 12, 17, 17],
       [40, 39, 46,  7, 26,  2,  1, 35],
       [24,  8, 35, 27, 44, 38, 17, 31],
       [33, 16, 38,  8, 32, 42, 18, 34],
       [ 9, 10, 14, 28,  5, 27, 33, 20],
       [18, 26, 41, 43, 15, 28, 32,  8]])

In [58]:
# YOUR CODE IS HERE (RESHAPING WITH -1)



In [59]:
ranarr.reshape(6,-1)

array([[27, 44,  1, 41, 20, 12, 17, 17],
       [40, 39, 46,  7, 26,  2,  1, 35],
       [24,  8, 35, 27, 44, 38, 17, 31],
       [33, 16, 38,  8, 32, 42, 18, 34],
       [ 9, 10, 14, 28,  5, 27, 33, 20],
       [18, 26, 41, 43, 15, 28, 32,  8]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [60]:
# YOUR CODE IS HERE 
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [61]:
# YOUR CODE IS HERE 
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [62]:
# YOUR CODE IS HERE 
mat[:,0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [63]:
# YOUR CODE IS HERE 
mat[1,0::2]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [64]:
# YOUR CODE IS HERE 
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [65]:
# YOUR CODE IS HERE 
mat[(1,3),(0,2)]

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [66]:
mat[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

In [67]:
# YOUR CODE IS HERE 


## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [68]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [69]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 

mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [70]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [71]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

mat[mat<10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [72]:
# YOUR CODE IS HERE 

(mat[mat<10] + mat[mat>12]).std()

29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [73]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [74]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 

# YOUR CODE IS HERE 
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [75]:
# YOUR CODE IS HERE 

mat[:,1].sum()

32

### 23. Get the median, mean and std of 3rd column in "mat".

In [76]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [77]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 

mat1 = mat[:,[2]]
mat1

array([[ 3],
       [ 7],
       [11],
       [15]])

In [78]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 

mat2 =mat[2,]

In [79]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 

print(np.median(mat1))
print(np.median(mat2))

9.0
10.5


In [80]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 

print(np.mean(mat1))
print(np.mean(mat2))

9.0
10.5


In [81]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 

print(np.std(mat1))
print(np.std(mat2))

4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [1]:
# YOUR CODE IS HERE 

import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [2]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 
pd.read_csv("Salaries.csv")

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [3]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE

pd.head()

AttributeError: module 'pandas' has no attribute 'head'

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 



Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
# YOUR CODE IS HERE 



In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 



### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 



### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE 



### How much does ALBERT PARDINI make money (including benefits)?

In [ ]:
# YOUR CODE IS HERE 



### Who is the lowest paid person?

In [ ]:
# YOUR CODE IS HERE 



### What are the unique Jobs in dataset?

In [ ]:
# YOUR CODE IS HERE 



### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE 



### How many people earned more than avg in 2012?

In [ ]:
# YOUR CODE IS HERE 



### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION FOR THIS QUESTION!

# YOUR CODE IS HERE 



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________